version: '3'

volumes:
  postgres-data:
  redis-data:

services:
  proxy:
    image: nginx:latest
    container_name: proxy
    restart: unless-stopped
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/sites-enabled:/etc/nginx/sites-enabled
      - ./proxy/sites.template.${SITES_TEMPLATE:-docker}:/etc/nginx/sites-available/sites.template
      - ./proxy/default/html:/var/www/html
      - ./proxy/log/nginx:/var/log/nginx
      - ./proxy/letsencrypt/:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HOSTNAME=${HOST_NAME:-xlab.blindside-dev.com}
    depends_on:
      - sakai
    command: /bin/bash -c "envsubst '$$NGINX_HOSTNAME' < /etc/nginx/sites-available/sites.template > /etc/nginx/sites-enabled/sites.conf && exec nginx -g 'daemon off;'"
    logging:
      driver: journald

# docker run --name mariadb -v /home/ubuntu/abc101/docker-data/mariadb:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=password -p 3306:3306 -d abc101/mariadb:10.5-buster --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode
  mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: always
    volumes:
        - ./mariadb/bin/init.sql:/data/application/init.sql
        - ./mariadb/data/:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: password
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--init-file=/data/application/init.sql']

  # mysql:
  #   image: mysql:5.7
  #   container_name: mysql
  #   restart: always
  #   # ports:
  #   #   - "33061:3306"
  #   volumes:
  #       - ./mysql/bin/init.sql:/data/application/init.sql
  #       - ./mysql/data/:/var/lib/mysql
  #   environment:
  #       MYSQL_ROOT_PASSWORD: password
  #   command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--init-file=/data/application/init.sql']

# docker run --name sakai --link mariadb:db -p 8080:8080 -it abc101/sakai:20.1
  sakai:
    image: abc101/sakai:20.1
    container_name: sakai
    restart: always
    ports:
      - "8080:8080"
    links:
      - "mariadb:db"
    depends_on:
      # - mysql
      - mariadb
